# Generated by Django 6.0.1 on 2026-01-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albara',
            name='data_entrega_prevista',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
