# Generated by Django 6.0.1 on 2026-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0002_alter_albara_data_entrega_prevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albara',
            name='estat',
            field=models.CharField(choices=[('PENDENT', 'Pendent'), ('EN_PREPARACIO', 'En Preparació'), ('ENVIAT', 'Enviat'), ('ENTREGAT', 'Entregat'), ('CANCELAT', 'Cancel·lat')], default='PENDENT'),
        ),
    ]
