# Generated by Django 6.0.1 on 2026-01-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0003_alter_albara_estat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiniaAlbara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField()),
                ('quantitat', models.IntegerField()),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, null=True)),
                ('albara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='mp_app.albara')),
            ],
        ),
        migrations.DeleteModel(
            name='LlineaAlbara',
        ),
    ]
